### ISSUE TITLE
Add compatibility with BasicStepperDriver

### ISSUE THREAD

**Issue by Boia11** [ArminJo/DigistumpArduino#1]
Hi!
Good job man......thanks for your help.
I need help for use Attiny85 with the [BasicStepperDriver](https://github.com/laurb9/StepperDriver)

The console return this when try to compile:
```
Arduino:1.8.12 (Windows 10), Scheda:"Digispark (Default - 16.5mhz)"

C:\Users\Simone\AppData\Local\Temp\ccsPwu2G.ltrans0.ltrans.o: In function `delayMicros':

C:\Users\Simone\Documents\Arduino\libraries\StepperDriver-1.2.0\src/BasicStepperDriver.h:46: undefined reference to `yield()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Errore durante la compilazione per la scheda Digispark (Default - 16.5mhz).
```
Can you do something?
Thanks in advance

**Comment by ArminJo** [comment]
I patched the Library.
you must delete the current library content under C:\Users\...\AppData\Local\Arduino15\packages\digistump completly, and the reinstall digispark avr again with the board manager.
The error should be fixed then.
Good Luck

**Comment by Boia11** [comment]
Perfect...now work.
Thank you man!
