### ISSUE TITLE
Where is the documentation for the Digispark keyboard / mouse?

### ISSUE THREAD

**Issue by elesto** [ArminJo/DigistumpArduino#11]
I have searched high and low for them but I cant find any. Im looking for explanations on how to use the new digikeyboard / mouse library.

**Comment by maxgerhardt** [comment]
Do you have a specific question on how to use a part of the library?

Both of the libraries have one example sketch, see `examples/` folder in 

https://github.com/ArminJo/DigistumpArduino/tree/master/digistump-avr/libraries/DigisparkKeyboard

https://github.com/ArminJo/DigistumpArduino/tree/master/digistump-avr/libraries/DigisparkMouse

The primary documentation would be the code / header file giving you a list of all available functions and their accepted parameters.

https://github.com/ArminJo/DigistumpArduino/blob/master/digistump-avr/libraries/DigisparkKeyboard/DigiKeyboard.h

https://github.com/ArminJo/DigistumpArduino/blob/master/digistump-avr/libraries/DigisparkMouse/DigiMouse.h

**Comment by elesto** [comment]
For some reason my digispark keyboard example file is not the same as the one you linked. It is missing the  //#define layouts and a few other lines. I have updated everything

**Comment by ArminJo** [comment]
This is correct, the changes are not yet contained in a release.
