### ISSUE TITLE
French Layout error in 1.7.3

### ISSUE THREAD

**Issue by BLurRPC** [ArminJo/DigistumpArduino#15]
Hello,
When I'm compiling with french layout on the version 1.7.3, there is an error saying TILDE_BITS not defined.
There is the same error for all frenches variations (canadian, belgium, ...).

The version 1.7.2 doesn't have this issue.

**Comment by ArminJo** [comment]
Hi,
I updated the repository with a new version of keylayouts.h.
Can you do me a favor and please check if they work and maybe the other french variants too?
If you give me the OK, I will include it in the release.

**Comment by BLurRPC** [comment]
Hello,
I checked it it's working well.
Thank you :)
