### ISSUE TITLE
"Please import the SPI library"

### ISSUE THREAD

**Issue by eadgbear** [ArminJo/DigistumpArduino#18]
Thanks for putting together this repo! It's help get me unblocked on using the Digistump Pro with MySensors. The one thing that I still seem to be missing is SPI.

A simple sketch for repro:
```C
#include <SPI.h>


void loop(){
    }

void setup(){
    }
```
Compiles just fine for the UNO, but with the Digispark Pro selected:

```
Alternatives for SPI.h: []sketch_apr07a:1:10: fatal error: Please import the SPI library from the Sketch > Import Library menu.
As of Arduino 0019, the Ethernet library depends on the SPI library.
You appear to be using it or another library that depends on the SPI library.
```

Any help would be appreciated.

**Comment by ArminJo** [comment]
Try to include TinySoftwareSPI.h instead of SPI.h

**Comment by eadgbear** [comment]
That seems to have done the trick! Thanks
