### ISSUE TITLE
German Keyboard Layout is off

### ISSUE THREAD

**Issue by alexg-k** [ArminJo/DigistumpArduino#19]
When I choose to compile with: `#define LAYOUT_GERMAN` and having the keyboard layout in Linux set to German, I get the some characters wrong.

For example the line `DigiKeyboard.print("<>");` results in the output: `/{` on my system.

I am so sorry to not help you more, but I have no clue how these keycodes work. Though I noticed that this [header-file](https://github.com/timmyRS/Digispark-German-Keyboard-API/blob/master/GermanKeyboard.h) does seem to do the trick.

**Comment by ArminJo** [comment]
And why do you open the issue here and not at https://github.com/timmyRS/Digispark-German-Keyboard-API ?

**Comment by alexg-k** [comment]
Let me try to rephrase: With this repo I get the unexpected result from above. With the linked header-file, I get the correct output.

I referenced the other repo with the header-file, so that maybe you can find the bug more easily.

**Comment by ArminJo** [comment]
And what is the output of the Keyboard example if you attach it to a Linux and what, if you attach it to a Windows PC?
And which core version do you use?

**Comment by alexg-k** [comment]
I tried the example from my first post on a linux machine and a Windows VM and both gave me back the result from above.

`DigiKeyboard.print("<>");` in both systems resulted in the keyboard output : `/{`

Sorry, I forgot: Core version is 1.7.2

**Comment by ArminJo** [comment]
If you do not want to answer my questions, I do not want to support you!
