### ISSUE TITLE
Clock setting not supported when uploading via programmer

### ISSUE THREAD

**Issue by Ircama** [ArminJo/DigistumpArduino#20]
# Clock setting not supported when uploading via programmer

Version 1.7.4 also includes the nice possibility to upload via programmer other than using the bootloader (e.g., version 1.7.2 did not).

Anyway, the clock setting does not work.

### Board
ATtiny85 Digispark board
Arduino Nano as ISP

### IDE
Arduino IDE

### Version
Version 1.7.4 

### Settings

File > Preferences > Additional Board manager URLs: 
https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json

Tools > Board: "Digispark"

Tools > Clock > 8 MHz – No USB (I use "8 MHz – No USB" after setting lfuse to E2 with `avrdude -Cavrdude.conf -v -pattiny85 -cstk500v1 -P... -b19200 -U lfuse:w:0xE2:m`)

Tools > Micronucleus variant: at the moment, the highest available option is just "aggressive" (notice the double `g` glitch BTW): there is no way to use the entire space, which would be possible using an ISP

Tools > Burn Bootloader Method: usage of this setting is not clear; at the moment it does not appear to influence the result

Tools > Port (I set the one connected to the Arduino Nano used as ISP)

Tools > Programmer: "Arduino as ISP"

To test, I use the "blink" sample sketch by measuring the LED timing, which is correct when the device is run at the standard clock (16.5 MHz with `-U lfuse:w:0xf1:m` fuse and "16.5 MHz for V-USB" setting), while incorrect in the above-mentioned example (16.5 MHz with `-U lfuse:w:0xE2:m` fuse and "8 MHz – No USB" setting).

As the result of Sketch > Upload is always to run the micronucleus (regardless of the setting "Tools > Programmer" - this would be another issue), the only way to run the programmer is via "Sketch > Upload Using Programmer".

Anyway, the behaviour is the same of running "Sketch > Upload" and then running *avrdude* manually on the compiled code.

Notice that *https://github.com/damellis/attiny* correctly works via "Sketch > Upload".

**Comment by ArminJo** [comment]
This must be a misunderstanding.
There is **no support for programming a sketch by ISP**, only support for uploading the **bootloader by ISP** was added.
For different board clocks and sketch programming by ISP, please use https://github.com/SpenceKonde/ATTinyCore.
