### ISSUE TITLE
CRC error while installing Digistump AVR Boards version 1.7.0

### ISSUE THREAD

**Issue by Ircama** [ArminJo/DigistumpArduino#3]
In https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json, the CRC 
*"checksum": "SHA-256:7ee55b9f7345fee70791d025de4be0b6f797f40ea34445d8a23846426a42775b"* does not seem to reflect https://github.com/ArminJo/DigistumpArduino/raw/master/digistump-avr-1.7.0.zip.

Version 1.6.8 works.

**Comment by ArminJo** [comment]
Thanks for QA! I missed to push the SHA changes. 
Now fixed (amended).

**Comment by Ircama** [comment]
Thanks and congratulations on this excellent repository!
