### ISSUE TITLE
package_sparkfun_index.json causes problems

### ISSUE THREAD

**Issue by gitterman** [ArminJo/DigistumpArduino#31]
## Bug Report
After adding 
I get error messages like this when I try to update libraries in the 1.8.18 IDE on windows
Index error: could not find referenced tool name=arm-none-eabi-gcc version=9-2019q4 packager=adafruit
Index error: could not find referenced tool name=nrfjprog version=9.4.0 packager=adafruit
Index error: could not find referenced tool name=CMSIS version=5.7.0 packager=adafruit
Index error: could not find referenced tool name=arm-none-eabi-gcc version=9-2019q4 packager=adafruit
Index error: could not find referenced tool name=nrfjprog version=9.4.0 packager=adafruit
Index error: could not find referenced tool name=CMSIS version=5.7.0 packager=adafruit
Index error: could not find referenced tool name=arm-none-eabi-gcc version=9-2019q4 packager=adafruit
Index error: could not find referenced tool name=nrfjprog version=9.4.0 packager=adafruit
Index error: could not find referenced tool name=CMSIS version=5.7.0 packager=adafruit_

As stated here: https://forums.adafruit.com/viewtopic.php?f=25&t=177076 the problem is due to the 
https://raw.githubusercontent.com/ArminJo/DigistumpArduino/master/package_digistump_index.json file.

Please have look into this.

### IDE
* [*] Arduino IDE

### Version
* [*] Yes I use the latest core version  and verified this!

**Comment by ArminJo** [comment]
I believe, you placed the issue in the wrong repository.
