### ISSUE TITLE
Digispark not recognized 

### ISSUE THREAD

**Issue by MuddyBTW** [ArminJo/DigistumpArduino#39]
Anyone knows how to fix this problem had it for some time 

Plug in device now... (will timeout in 60 seconds)
Please plug in the device ... 
Press CTRL+C to terminate the program.
Device search timed out

It doesn't get recognized by my computer I don't know why iv tried to fix but cant

**Comment by ArminJo** [comment]
Try another port, another computer, or an USB Hub.
