### ISSUE TITLE
DigiKeyboard.sendKeyStroke doesn´t work

### ISSUE THREAD

**Issue by JanF-04** [ArminJo/DigistumpArduino#4]
Dear Sir or Madame,

I want to send following key stroke:
DigiKeyboard.sendKeyStroke(KEY_M , MOD_CONTROL_LEFT | MOD_SHIFT_LEFT);
But it returns:
Key.ctrl_l + Key.shift + '\r'
How can I solve the Problem? I tried many things, even reinstalling the Digispark libraries.

Additionally the digispark USB Device turns off after about half an hour? Is there a way changing the times or even setting them to infinite?

Thanks for helping
Kind regards
Jan Fenten

**Comment by Cosmoledo** [comment]
Hey, what language layout are you using? What letter should be printed with the key combination of M + Control + Shift?

I am certain there is a bug in keylayout.h in this repo, so reinstalling shouldn't change anything.

You could try to use an earlier release/commit or switch to [rsrdesarrollo](https://github.com/rsrdesarrollo/DigistumpArduino) or the [official version,](https://github.com/digistump/DigistumpArduino) which does not support multi layout.

**Comment by JanF-04** [comment]
I want to mute myself in Teams... I am using the default Arduino IDE, so C/C++. How to use the earlier commit?
And do you know why the devices turns off after about half an hour?

**Comment by Cosmoledo** [comment]
Oh, I meant which keyboard layout are you using. If you use the default english one, try the official library. Remove the current one in Board Manager, change the Board Manager URL and download the official one, maybe that would help. If you use a special layout, you could try the other mentioned library.

I don't know why it shuts down after some time, I just have it active for some minutes.
