### ISSUE TITLE
Faulty language codes and path clipping in bootloader update

### ISSUE THREAD

**Issue by jonathanothen** [ArminJo/DigistumpArduino#42]
### Board
* [x ] Digispark

### IDE
* [x ] Arduino IDE

### Example from the core libraries to reproduce the issue
#define LAYOUT_SWEDISH
#define LAYOUT_NORWEGIAN
#define LAYOUT_DANISH

### Version
* [x ] Yes I use the latest core version  and verified this!

### Current behavior
Wasn't able to use any of the nordic languages, probably due to missing å, ä and ö in the Teensyduino library, getting errors like "error: narrowing conversion of '1068' "

Also had a problem with updating the bootloader,Arduino IDE is capping the path for the bootloaders in the path name:
Correct: C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump...
Path trying to fetch from: Othén\AppData\Local\Arduino15\packages\digistump...

(can't remeber the whole path by my mind)

Had to reinstall the original repository so sorry for incomplete  info.

**Comment by jonathanothen** [comment]
Might add that none of the other layouts had any problems.

**Comment by ArminJo** [comment]
> Wasn't able to **use** any of the nordic languages.

Maybe you use it wrong?

**Comment by jonathanothen** [comment]
Doesn't explain why all other languages work. Error with swedish, exact same code except the #define LAYOUT_xxx

Mabye you have a clue what i'm doing wrong then?

Best regards.

In file included from C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.5\libraries\DigisparkKeyboard/DigiKeyboard.h:17:0,
                 from C:\Users\Jonathan Othén\Documents\Arduino\Test\Test.ino:29:
C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.5\libraries\DigisparkKeyboard/keylayouts.h:5366:1: error: narrowing conversion of '1068' from 'unsigned int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
 };
 ^
C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.5\libraries\DigisparkKeyboard/keylayouts.h:5366:1: error: narrowing conversion of '1836' from 'unsigned int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.5\libraries\DigisparkKeyboard/keylayouts.h:5366:1: error: narrowing conversion of '3072' from 'int' to 'uint8_t {aka unsigned char}' inside { } [-Wnarrowing]
Using library DigisparkKeyboard in folder: C:\Users\Jonathan Othén\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.7.5\libraries\DigisparkKeyboard (legacy)
exit status 1
Error compiling for board Digispark.

**Comment by ArminJo** [comment]
> Mabye you have a clue what i'm doing wrong then?

Yes. Please get the latest files from the repo, the bug is fixed, but not released..
