### ISSUE TITLE
Help for detecting wrong keylayouts

### ISSUE THREAD

**Issue by Cosmoledo** [ArminJo/DigistumpArduino#5]
Hey, thanks for your work, but in the german language there are some mistakes again. To help you find them faster, I have written a simple tool, take a look at it [here](https://github.com/Cosmoledo/DigiKeyboardTester). I hope, you can use it to fix the wrong letters. I tried it myself but I miss the knowledge.

**Comment by ArminJo** [comment]
Thanks a lot.
I hope I will get time this week to test it.
