### ISSUE TITLE
Permission denied during uploading

### ISSUE THREAD

**Issue by H4D3SPH4NT0M** [ArminJo/DigistumpArduino#51]
If you have handling problems or questions, consider to open a discussion https://github.com/ArminJo/DigistumpArduino/discussions instead of an issue.

### Board
* [X] Digispark
* [ ] Arduino Pro
* [ ] MH-ET LIVE Tiny88

### IDE
* [X] Arduino IDE
* [ ] Arduino Web Editor
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### Version
* [X] Yes I use the latest core version  and verified this!
* [ ] Other - please specify

Please delete all unchecked lines above :-)

### Current behavior

I'm trying to upload a sketch but i keep getting this error saying: 

**usb_open(): Permission denied. For Linux, copy file https://github.com/micronucleus/micronucleus/blob/master/commandline/49-micronucleus.rules to /etc/udev/rules.d.**

I have tried changing the permission of /etc/udev/rules.d i even reinstalled the whole arduino ide but i still have the same problem any help is appreciated!

**Comment by ArminJo** [comment]
Please do not open an issue for your personal linux problems!
