### ISSUE TITLE
SPI.h Not found when using Adafruit Dotstar Library

### ISSUE THREAD

**Issue by MatthewMartinFD** [ArminJo/DigistumpArduino#56]
If you have handling problems or questions, consider to open a discussion https://github.com/ArminJo/DigistumpArduino/discussions instead of an issue.

### Board
* [X] Digispark

### IDE
* [X] Arduino IDE

### Version
* [X] Yes I use the latest core version  and verified this!
Using 1.7.5 installed fresh today, 1/21/2023

### Current behavior

```
#include <Adafruit_DotStar.h>

void setup() {
  // put your setup code here, to run once:
}

void loop() {
  // put your main code here, to run repeatedly:
}
```

```In file included from c:\Users\Deviant\Documents\Arduino\libraries\Adafruit_DotStar/Adafruit_DotStar.h:26:0,
                 from C:\Users\Deviant\AppData\Local\Temp\.arduinoIDE-unsaved2023021-13512-sdcgw0.51dq\sketch_jan21a\sketch_jan21a.ino:1:
c:\Users\Deviant\Documents\Arduino\libraries\Adafruit_BusIO/Adafruit_SPIDevice.h:9:10: fatal error: SPI.h: No such file or directory
 #include <SPI.h>
          ^~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1
```

When attempting to compile using the Digispark board and including Adafruit_Dotstar.h from Adafruit Dotstar v1.2.1, SPI.h cannot be found
### Expected behavior

Full compile without errors.

**Comment by ArminJo** [comment]
Is Adafruit Dotstar released for ATtiny85?

**Comment by MatthewMartinFD** [comment]
I have a physical device that was previously working with a Dotstar attached to a digispark, however its bootloader became corrupted and I need to compile software onto a replacement.  So this works in some capacity, I can't speak to your statement specifically.

**Comment by MatthewMartinFD** [comment]
It appears to compile if I downgrade Adafruit_DotStar to 1.1.4, though I am waiting for new hardware to come in the mail to test.

**Comment by ArminJo** [comment]
Thanks! 
So it seems to be no problem with DigistumpArduino but with Adafruit_DotStar.
Try also the [ATTinyCore](https://github.com/SpenceKonde/ATTinyCore) for it.
