### ISSUE TITLE
Build for ARM (M1/M2) CPU on OSX

### ISSUE THREAD

**Issue by spuder** [ArminJo/DigistumpArduino#57]
Attempting to use this library in platformio.ini on OSX on a Mac with M1 processor produces this error

```
Processing digispark-tiny (platform: atmelavr; board: digispark-tiny; framework: arduino)
----------------------------------------------------------------------------------
Tool Manager: Installing platformio/framework-arduino-avr-digistump @ ^1.7.6
Error: Could not find the package with 'platformio/framework-arduino-avr-digistump @ ^1.7.6' requirements for your system 'darwin_arm64'
```

## Steps to reproduce

```
[env:digispark-tiny]
platform = atmelavr
board = digispark-tiny
framework = arduino
build_flags = 
	-D LED_PIN=1
platform_packages =
	platformio/framework-arduino-avr-digistump@^1.7.6
```

Then attempt to build, and you will see this error. 

If you have handling problems or questions, consider to open a discussion https://github.com/ArminJo/DigistumpArduino/discussions instead of an issue.

### Board
* [x] Digispark
* [ ] Arduino Pro
* [ ] MH-ET LIVE Tiny88

### IDE
* [ ] Arduino IDE
* [ ] Arduino Web Editor
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [x] PlatformIO IDE
* [ ] Other - please specify

### Version
* [x] Yes I use the latest core version  and verified this!
* [ ] Other - please specify

**Comment by ArminJo** [comment]
RTFM please.
