### ISSUE TITLE
Disappeared "Plug in device now..."

### ISSUE THREAD

**Issue by woodlist** [ArminJo/DigistumpArduino#60]
If you have handling problems or questions, consider to open a discussion https://github.com/ArminJo/DigistumpArduino/discussions instead of an issue.

### Board
* [*] Digispark
* [ ] Arduino Pro
* [ ] MH-ET LIVE Tiny88

### IDE
* [*] Arduino IDE 2.3.2 
* [ ] Arduino Web Editor
* [ ] Arduino Pro IDE
* [ ] Sloeber IDE
* [ ] PlatformIO IDE
* [ ] Other - please specify

### Version
* [*] Yes I use the latest core version  and verified this!
* [ ] Other - please specify

Please delete all unchecked lines above :-)

### Current behavior
` #include <Tachometer.h>  // https://github.com/GyverLibs/Tachometer?tab=readme-ov-file
Tachometer tacho;

void setup() {
  // put your setup code here, to run once:
pinMode(0, INPUT_PULLUP);
pinMode(1, OUTPUT);
attachInterrupt(0, isr, FALLING);
}

void loop() {
  // put your main code here, to run repeatedly:
  if (tacho.getHz() > 95) digitalWrite (1, HIGH);
  else digitalWrite (1, LOW);
}

void isr() {
  tacho.tick(); 
} 

 Sketch uses 2026 bytes (13%) of program storage space. Maximum is 14970 bytes.
Global variables use 29 bytes (5%) of dynamic memory, leaving 483 bytes for local variables. Maximum is 512 bytes.
"C:\Users\woodl\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.6/micronucleus" --no-ansi --run --timeout 60 C:\Users\woodl\AppData\Local\Temp\arduino\sketches\3727D12B961B500C998C67424C146797/digispark_interrupt.ino.hex
Failed uploading: uploading error: exit status 0xc0000135. `

The board is programmable on Arduino 1.8.17 on Win10, but falls on Arduino IDE 2.3.2 on Win11

**Comment by ArminJo** [comment]
RTFM!

**Comment by woodlist** [comment]
> RTFM!

It is the first time I met this abbreviation and Copliot helped answer means I missed to read something in manual. However, please, directly refer to somewhat defined, if it is available. I am not alone in this trouble- [https://stackoverflow.com/questions/75775009/digispark-arduino-ide-upload-error-exit-status-0xc0000135](url)

**Comment by woodlist** [comment]
I have fixed this issue by myself ACCIDENTALLY. My computer has only USB3.0 ports and this was the root of the problem. Having connected via USB 2.0 hub the trouble gone.
