### ISSUE TITLE
Uploader doesn't know how to upload

### ISSUE THREAD

**Issue by atomspring** [ArminJo/DigistumpArduino#7]
Hello @ArminJo , thanks for writing this tool.

I recently bought a digispark, setting up the host system per the instructions on Digistump's site (adding a udev rule etc), and then adding your package index into Arduino 1.18.13 (latest).

When I first burned the bootloader, the steps went great, though I left the variant at 'Default', not 'Recommended'.

Now when I try to upload a sketch, or burn a different bootloader, I get these messages repeating:

> 
> /home/atomspring/.arduino15/packages/digistump/tools/micronucleus/2.0a4/launcher -cdigispark --timeout 60 -Uflash:w:/home/atomspring/.arduino15/packages/digistump/hardware/avr/1.7.0/bootloaders/upgrade-t85_entry_on_powerOn_activePullup_fastExit.hex:i 
> 
> Running Digispark Uploader...
> 
> Plug in device now... (will timeout in 60 seconds)
> 
> Warning: device with unknown new version of Micronucleus detected.
> This tool doesn't know how to upload to this new device. Updates may be available.
> Device reports version as: 2.5
> 
> Warning: device with unknown new version of Micronucleus detected.
> This tool doesn't know how to upload to this new device. Updates may be available.
> Device reports version as: 2.5

What do I do here?

**Comment by ArminJo** [comment]
Hi,
Did you try this binaries? https://github.com/stonehippo/micronucleus-commandline-builds
They are the latest ones.

**Comment by ArminJo** [comment]
I can reproduce your error but still looking for a solution.

**Comment by ArminJo** [comment]
[Here](https://github.com/ArminJo/micronucleus-firmware/tree/master/commandline/builds) are the new binaries

**Comment by ArminJo** [comment]
A new 1.7.1 version with new packaged binaries is released
