### ISSUE TITLE
A new way to burn default bootloader by Arduino ISP

### ISSUE THREAD

**Issue by LiHangBing** [ArminJo/DigistumpArduino#8]
If USB bootloader don't work, mabye ISP is OK. 
Use Arduino ISP can also burn the USB bootloader and reset Fuse.
Because there is something wrong with the  [official](https://github.com/ArminJo/micronucleus-firmware/tree/master/utils)
see here:
https://blog.csdn.net/Argon_Ghost/article/details/103637870
hope you can understand or translate it.

command is here:
C:\Sofware_Portable\arduino-1.8.8\hardware\tools\avr/bin/avrdude -C "C:\Sofware_Portable\arduino-1.8.8\\hardware\tools\avr/etc/avrdude.conf" -v -pattiny85 -carduino -PCOM4 -b19200 -Uflash:w:C:\Storage\t85_default.hex:i -U lfuse:w:0xE1:m -U hfuse:w:0xDD:m -U efuse:w:0xFE:m
just replace "C:\Sofware_Portable\arduino-1.8.8", "-PCOM4" and "C:\Storage\t85_default.hex" with your file and directory

**Comment by ArminJo** [comment]
The BOD is disabled intentionally to save power for ultra low power applications
