### ISSUE TITLE
Installation instructions for PlatfomIO

### ISSUE THREAD

**Issue by anno73** [ArminJo/DigistumpArduino#9]
I am currently in an ATTiny85 dev project in platformio and I would like to give your core a try. Could you please provide instructions on how to install your core in pio? Or possibly even better, request integration to pio by raising a feature request there?

**Comment by ArminJo** [comment]
Do you now where there is?

**Comment by anno73** [comment]
I have seen avr board addition request in https://github.com/platformio/platform-atmelavr/issues.

**Comment by ArminJo** [comment]
Thanks, I will request integration for it. I am not familiar with pio, I love [Sloeber](https://eclipse.baeyens.it/)!
